---
- name: Setup Windows VM
  hosts: all
  tasks:
    - name: Install IIS Web Server
      win_feature:
        name: Web-Server
        state: present

    - name: Ensure IIS is running
      win_service:
        name: W3SVC
        start_mode: auto
        state: started
