name: Build Packer Image and deploy VM

on:
    push:
        branches:
            - test

jobs:
    packer:
        name: Build windows image and Publish Image to SIG
        runs-on: self-hosted

        strategy:
            matrix:
                environment:
                    - windows2019
                    - RHEL
                    - windows2022
                    #- windowsimages

        env:
            ROOT_PATH: ${{ github.workspace }}/${{ matrix.environment }}

        permissions:
            id-token: write
            contents: read

        steps:
          - name: Checkout repository
            uses: actions/checkout@v2

          - name: Set up Packer
            uses: hashicorp/setup-packer@v2

          - name: Authenticate to Azure
            uses: azure/login@v2
            with:
             auth-type: IDENTITY
             client-id: ${{ secrets.AZURE_CLIENT_ID1 }}
             tenant-id: ${{ secrets.AZURE_TENANT_ID1 }}
             subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID1 }}

          - name: Init Packer image
            working-directory: ${{ env.ROOT_PATH }}
            run: 
             packer init .

          - name: fmt Packer image
            working-directory: ${{ env.ROOT_PATH }}
            run: 
             packer fmt .

          - name: validation Packer image
            working-directory: ${{ env.ROOT_PATH }}
            run: 
             packer validate .

          - name: Build Packer image
            working-directory: ${{ env.ROOT_PATH }}
            run: 
             packer build .
