name: Build Packer Image

on:
  push:
    branches:
      #- main
       - test
jobs:
  build:
    runs-on: [self-hosted,test]
    env:
      ROOT_PATH : '${{github.workspace}}/windows'

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Packer
      uses: hashicorp/setup-packer@v2

    - name: Authenticate to Azure 
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
    - name: Init Packer image
      working-directory: ${{env.ROOT_PATH}}
      run: 
        packer init .

    - name:  Build Packer image
      working-directory: ${{env.ROOT_PATH}}
      run:
        packer build .