name: Terraform deploy

on:
    push:
        branches:
          #- main
           - test
jobs:
 terraform:
    name: Deploy VM using SIG
    runs-on: [Linux] #[self-hosted,test]
    defaults:
        run:
            shell: bash
            working-directory: '${{github.workspace}}/terraform-poc' 
        
    env:
      #ROOT_PATH : '${{github.workspace}}\terraform-poc' 
      TF_LOG: INFO
    permissions:
      id-token: write
      contents: read
    # needs: packer
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Set up Azure CLI
        uses: azure/login@v2
        with:
         client-id: ${{ secrets.AZURE_CLIENT_ID }}
         tenant-id: ${{ secrets.AZURE_TENANT_ID }}
         subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: 'Run Az commands'
        run: |
         az account show

      - name: Terraform Init 
        # working-directory: ${{env.ROOT_PATH}}
        env:
          STORAGE_ACCOUNT: "tfstatewells"
          CONTAINER_NAME: "terraform"
          RESOURCE_GROUP: "Test_VM"
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          #ARM_CLIENT_SECRET: ${{ secrets.AZURE_SECRET_ID}}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          
        run: terraform init -input=false -backend-config="resource_group_name=$RESOURCE_GROUP" -backend-config="storage_account_name=$STORAGE_ACCOUNT" -backend-config="container_name=$CONTAINER_NAME"  
        
        

        #Run Terraform Plan

      - name: Terraform plan
        
        working-directory: '${{github.workspace}}/terraform-poc' 
        run: 
         terraform plan -no-color
        env:
          STORAGE_ACCOUNT: ${{ secrets.BACKEND_AZURE_STORAGE_ACCOUNT_NAME }}
          CONTAINER_NAME: ${{ secrets.BACKEND_AZURE_STORAGE_ACCOUNT_CONTAINER_NAME }}
          RESOURCE_GROUP: ${{ secrets.BACKEND_AZURE_RESOURCE_GROUP_NAME }}
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        
  
       # Run Terraform apply
      - name: Terraform Apply
        
        working-directory: '${{github.workspace}}/terraform-poc'
        run: 
         terraform apply -auto-approve
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}


      - name: Create a Text File
        run: echo "This is the content of the file." > myfile.txt
   
      - name: Display the File Content
        run: cat myfile.txt     
      

      - name: Install Ansible
        run: |
            sudo apt update
            sudo apt install -y ansible jq    

      - name: Create Dynamic Inventory
        run: |
          echo "MY_VAR=Hello from GitHub Actions!">> inventory.ini    

      - name: Get private IP address
        id: get_ip
        run: |
            VM_PRIVATE_IP=$(terraform output -raw vm_private_ip || echo "no-ip")
            echo "VM_PRIVATE_IP=${VM_PRIVATE_IP}" >> $GITHUB_ENV
            
    
      - name: Create Dynamic Inventory
        run: |
          echo "hello world" >> inventory.ini
          # echo "my_windows_vm ansible_host=${{ env.vm_private_ip  }} ansible_user=adminuser  ansible_password="Welcome#2024" ansible_connection=winrm ansible_port=5985 ansible_winrm_server_cert_validation=ignore" >> inventory.ini
          # echo "Dynamic inventory created:"
          # cat inventory.ini  # Display the inventory for verification
    
      - name: Run Ansible Playbook
        working-directory: '${{github.workspace}}/ansible'
        run: |
          ansible-playbook -i inventory.ini setup_vm.yml

    